# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI/CD ConvManAPI - DEV - TEST Artifact

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build-prod --if-present
          npm run test --if-present

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip api for upload
        run: zip -qq -r api-artifact.zip dist node_modules package.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: api-artifact
          path: api-artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: api-artifact

      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq api-artifact.zip -d .

      - name: move dist to the root directory
        run: mv ./dist/* .

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "convmanapi-dev"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EB2B0B76DA3F4999ADC4B8EB039558BB }}
          package: .
